apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apm-helper
  name: apm-helper
spec:
  containers:
    - image: whatap/apm-find-containerid:3.0.2
      name: apm-find-containerid
      resources: {}
      env:
        - name: get_apm_container_id_using_whatap
          value: "true"
        - name: NODE_IP
          valueFrom: { fieldRef: { fieldPath: status.hostIP } }
        - name: NODE_NAME
          valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
        - name: POD_NAME
          valueFrom: { fieldRef: { fieldPath: metadata.name } }
      volumeMounts:
        - name: whatap
          mountPath: /whatap
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
    - name: whatap
      hostPath:
        path: /whatap
status: {}